CC = gcc
ICS = ..
CFLAGS = -Wall -O2

PROGS = sumvec\
	sumarrayrows\
	sumarraycols\
	sumarray3d\
	sumarray3d-ans\
	dotprod\
	cleararray\
	simaquarium.o\
	postit.o\
	game.o\
	transpose1.o\
	transpose2.o\
	optlab.o\


all: $(PROGS)

clean:
	rm -f $(PROGS) *.o *~


